<?php
/**
 * EnergyEfficiency
 *
 * PHP version 5
 *
 * @category Class
 * @package  Enbisys\Avm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Enbisys\Avm\Model;
use \Enbisys\Avm\ObjectSerializer;

/**
 * EnergyEfficiency Class Doc Comment
 *
 * @category Class
 * @package  Enbisys\Avm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EnergyEfficiency
{
    /**
     * Possible values of this enum
     */
    const AVERAGE = 'average';
    const GOOD = 'good';
    const POOR = 'poor';
    const VERY_GOOD = 'very_good';
    const VERY_POOR = 'very_poor';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AVERAGE,
            self::GOOD,
            self::POOR,
            self::VERY_GOOD,
            self::VERY_POOR,
        ];
    }
}


