<?php
/**
 * FloorLevel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Enbisys\Avm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Enbisys\Avm\Model;
use \Enbisys\Avm\ObjectSerializer;

/**
 * FloorLevel Class Doc Comment
 *
 * @category Class
 * @description Floor level
 * @package  Enbisys\Avm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FloorLevel
{
    /**
     * Possible values of this enum
     */
    const BASEMENT = 'basement';
    const GROUND = 'ground';
    const MIDDLE = 'middle';
    const TOP = 'top';
    const FLOOR_1 = 'floor_1';
    const FLOOR_2 = 'floor_2';
    const FLOOR_3 = 'floor_3';
    const FLOOR_4 = 'floor_4';
    const FLOOR_5 = 'floor_5';
    const FLOOR_6 = 'floor_6';
    const FLOOR_7 = 'floor_7';
    const FLOOR_8 = 'floor_8';
    const FLOOR_9 = 'floor_9';
    const FLOOR_10 = 'floor_10';
    const FLOOR_11 = 'floor_11';
    const FLOOR_12 = 'floor_12';
    const FLOOR_13 = 'floor_13';
    const FLOOR_14 = 'floor_14';
    const FLOOR_15 = 'floor_15';
    const FLOOR_16 = 'floor_16';
    const FLOOR_17 = 'floor_17';
    const FLOOR_18 = 'floor_18';
    const FLOOR_19 = 'floor_19';
    const FLOOR_20 = 'floor_20';
    const FLOOR_21_OR_ABOVE = 'floor_21_or_above';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BASEMENT,
            self::GROUND,
            self::MIDDLE,
            self::TOP,
            self::FLOOR_1,
            self::FLOOR_2,
            self::FLOOR_3,
            self::FLOOR_4,
            self::FLOOR_5,
            self::FLOOR_6,
            self::FLOOR_7,
            self::FLOOR_8,
            self::FLOOR_9,
            self::FLOOR_10,
            self::FLOOR_11,
            self::FLOOR_12,
            self::FLOOR_13,
            self::FLOOR_14,
            self::FLOOR_15,
            self::FLOOR_16,
            self::FLOOR_17,
            self::FLOOR_18,
            self::FLOOR_19,
            self::FLOOR_20,
            self::FLOOR_21_OR_ABOVE,
        ];
    }
}


