<?php
/**
 * PropertyType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Enbisys\Avm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Enbisys\Avm\Model;
use \Enbisys\Avm\ObjectSerializer;

/**
 * PropertyType Class Doc Comment
 *
 * @category Class
 * @description type of property
 * @package  Enbisys\Avm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PropertyType
{
    /**
     * Possible values of this enum
     */
    const FLAT = 'flat';
    const SEMI_DETACHED_HOUSE = 'semi_detached_house';
    const DETACHED_HOUSE = 'detached_house';
    const TERRACED_HOUSE = 'terraced_house';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FLAT,
            self::SEMI_DETACHED_HOUSE,
            self::DETACHED_HOUSE,
            self::TERRACED_HOUSE,
        ];
    }
}


