<?php
/**
 * WallType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Enbisys\Avm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Enbisys\Avm\Model;
use \Enbisys\Avm\ObjectSerializer;

/**
 * WallType Class Doc Comment
 *
 * @category Class
 * @package  Enbisys\Avm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WallType
{
    /**
     * Possible values of this enum
     */
    const CAVITY_WALL = 'cavity_wall';
    const COB = 'cob';
    const GRANITE_OR_WHIN = 'granite_or_whin';
    const PARK_HOME_WALL = 'park_home_wall';
    const SANDSTONE = 'sandstone';
    const SOLID_BRICK = 'solid_brick';
    const SYSTEM_BUILD = 'system_build';
    const TIMBER_FRAME = 'timber_frame';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CAVITY_WALL,
            self::COB,
            self::GRANITE_OR_WHIN,
            self::PARK_HOME_WALL,
            self::SANDSTONE,
            self::SOLID_BRICK,
            self::SYSTEM_BUILD,
            self::TIMBER_FRAME,
        ];
    }
}


