<?php
/**
 * WindowGlazingType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Enbisys\Avm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Enbisys\Avm\Model;
use \Enbisys\Avm\ObjectSerializer;

/**
 * WindowGlazingType Class Doc Comment
 *
 * @category Class
 * @package  Enbisys\Avm
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WindowGlazingType
{
    /**
     * Possible values of this enum
     */
    const SINGLE = 'single';
    const SECONDARY = 'secondary';
    const DOUBLE = 'double';
    const TRIPLE = 'triple';
    const MULTIPLE = 'multiple';
    const HIGH_PERFORMANCE = 'high_performance';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SINGLE,
            self::SECONDARY,
            self::DOUBLE,
            self::TRIPLE,
            self::MULTIPLE,
            self::HIGH_PERFORMANCE,
        ];
    }
}


